name: pis
services:
  postgres:
    image: pgvector/pgvector:pg16
    restart: always
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
      - ./init-postgresql-db.sql:/docker-entrypoint-initdb.d/01-init-postgresql-db.sql:ro
  redis:
    image: redis:7-alpine
    restart: always
    volumes: [./data/redis:/data]
  minio:
    image: minio/minio:RELEASE.2025-04-22T22-12-26Z
    restart: always
    volumes: [./data/minio:/data]
    command: ["server", "/data", "--console-address", ":9001"]
  worker:
    image: hub.albertzhan.top/pis/worker:latest
    restart: always
    depends_on: [postgres, minio, redis]
  web:
    image: hub.albertzhan.top/pis/web:latest
    restart: always
    depends_on: [postgres, worker]
    volumes: [./logs/web:/app/logs]
  nginx:
    image: nginx:alpine
    restart: always
    depends_on: [web, minio]
    ports: ["8088:80"]
    volumes: [./nginx/nginx.conf:/etc/nginx/nginx.conf:ro, ./nginx/conf.d:/etc/nginx/conf.d:ro]
